# Import necessary libraries
import json
import os
import torch

# Import necessary modules from the 'ontoaligner' library
# The library provides tools for ontology alignment tasks, including dataset management,
# encoding, retrieval, reranking, evaluation, and postprocessing.
from ontoaligner.encoder import ConceptParentLightweightEncoder
from ontoaligner.ontology import MaterialInformationMatOntoOMDataset
from ontoaligner.utils import metrics, xmlify
from ontoaligner.aligner import SBERTRetrieval, CohereReranking, CrossEncoderReranking
from ontoaligner.postprocess import retriever_postprocessor


# Step 1: Initialize the ontology matching task
# The task is created using the Material Information Ontology Dataset,
# which includes source and target ontologies and reference matchings for evaluation.
task = MaterialInformationMatOntoOMDataset()

# Confirm the task initialization by printing its details
print("Test Task:", task)

# Step 2: Collect the ontology dataset
# The dataset includes paths to the source ontology, target ontology, and reference matching files.
dataset = task.collect(
    source_ontology_path="assets/MI-MatOnto/mi_ontology.xml",
    target_ontology_path="assets/MI-MatOnto/matonto_ontology.xml",
    reference_matching_path="assets/MI-MatOnto/matchings.xml",
)

# Step 3: Select the runtime device
# The reranking example can use GPU if CUDA is available; otherwise, it runs on CPU.
device = "cuda" if torch.cuda.is_available() else "cpu"

# Step 4: Initialize the encoder model
# The encoder prepares source and target ontology concept texts for retrieval and reranking.
encoder_model = ConceptParentLightweightEncoder()

# Encode the source and target ontologies
# The output is used as input for the retrieval model.
source_onto, target_onto = encoder_model(source=dataset["source"],target=dataset["target"])

# Step 5: Set up the retrieval model
# The retrieval model generates candidate target concepts for each source concept.
# Here, SBERTRetrieval is used with the all-MiniLM-L6-v2 sentence-transformer model.
retriever = SBERTRetrieval(device=device, top_k=10)

# Load the SBERT retrieval model
retriever.load(path="all-MiniLM-L6-v2")

# Generate candidate alignments
# The retrieval model returns grouped candidates using source, target-cands, and score-cands.
retrieval_outputs = retriever.generate(input_data=[source_onto,target_onto])

# Step 6: Set up the reranking model
# The reranker refines the candidates generated by the retrieval model.
# CrossEncoderReranking scores each source-target pair jointly and reranks the retrieved candidates.
reranker = CrossEncoderReranking(
    device=device,
    top_k=5,
    normalize_score="sigmoid",
)

# Load the CrossEncoder reranking model
reranker.load(path="cross-encoder/ms-marco-MiniLM-L6-v2")

# To use Cohere reranking instead of CrossEncoderReranking, replace the block above with:
# reranker = CohereReranking(
#     cohere_key=os.environ["COHERE_API_KEY"],
#     top_k=5,
#     normalize_score="none",
# )
# # Load the Cohere reranking model
# reranker.load(path="rerank-v3.5")

# Step 7: Rerank the retrieved candidates
# The reranker preserves the retrieval output format, so the existing retriever_postprocessor
# can still be used after reranking.
reranked_outputs = reranker.generate(input_data=[source_onto,target_onto,retrieval_outputs])

# Step 8: Post-process the reranked outputs
# The retriever_postprocessor converts grouped candidates into flat source-target matchings.
# For CrossEncoderReranking with sigmoid normalization, threshold=0.5 can be used.
# For CohereReranking, threshold=0.0 keeps the reranked top-k candidates.
matchings = retriever_postprocessor(predicts=reranked_outputs,threshold=0.5)

# Step 9: Evaluate the generated matchings
# The evaluation report compares predicted matchings against the reference alignments
# using metrics such as precision, recall, and F-score.
evaluation = metrics.evaluation_report(predicts=matchings,references=dataset["reference"])

# Print the evaluation report in a human-readable JSON format
print("Evaluation Report:", json.dumps(evaluation, indent=4))

# Step 10: Export matchings in XML format or JSON format

# XML format
# Convert the generated matchings into an XML alignment file using the xmlify utility.
xml_str = xmlify.xml_alignment_generator(matchings=matchings)

# Save the XML alignment to a file for further use or analysis
output_file_path = "reranked_matchings.xml"
with open(output_file_path, "w", encoding="utf-8") as xml_file:
    xml_file.write(xml_str)

print(f"Matchings in XML format have been successfully written to '{output_file_path}'.")

# JSON format
# Save the generated matchings in dictionary format for further analysis or debugging.
output_file_path = "reranked_matchings.json"
with open(output_file_path, "w", encoding="utf-8") as json_file:
    json.dump(matchings, json_file, indent=4, ensure_ascii=False)

print(f"Matchings in JSON format have been successfully written to '{output_file_path}'.")